name: face
channels:
- conda-forge
- defaults
dependencies:
- joblib
- pip:
  - matplotlib
  - joblib
  - pathlib
  - keras
  - dlib
  - numpy
  - scipy
  - opencv
  - face_recognition
  - pandas
  - seaborn
  - plotly
  - PIL
  - pillow
  - os
  - cv2 
  - skimage
  - streamlit

