channels:
- conda-forge
- defaults
dependencies:
- joblib
- pip
- pip:
      - matplotlib
      - joblib
      - pathlib
      - keras
      - dlib
      - numpy
      - scipy
      - opencv
      - face_recognition
      - pandas
      - joblib
      - matplotlib
      - seaborn
      - plotly
      - PIL
      - pillow
      - os
      - cv2 
      - skimage

