 channels:
     - conda-forge
 dependencies:
     - pip:
      - matplotlib
      - pathlib
      - keras
      - dlib
      - numpy
      - scipy
      - opencv
      - face_recognition
      - pandas
      - joblib
      - matplotlib
      - seaborn
      - plotly
      - PIL
      - pillow
      - os
      - cv2 
      - skimage

